data_shape: [4, 48, 84, 5] # (n_bars, n_timesteps, n_pitches, n_tracks)
beat_resolution: 12 # number of time steps used to represent a beat
latent_dim: 128
is_conditional: false
is_accompaniment: false
condition_track_idx: ~
use_binary_neurons: false
nets:
  generator: default
  discriminator: default
